

Simulation:
  train_size: 128 # size of the images network see
  use_cell_bg: False
  density: 
  margin_empty: 0.05 # what percent of the image you want to leave empty on the image
  z_prior:
    - -1
    - 1
  survival_prob: # only used if there is local context, so in our case it is not used
  min_photon: 0.428 # intensity distributions sampled from (min_ph, 1)


Network:
  n_filters: 48
  n_stages: 2
  padding: 1
  kernel_size: 3
  sig_pred: True
  psf_pred: False
  local_context: False # This will just use 1 frame for context, always False for our use-case
  use_coordconv: False # Use if you want to add cell-bg coordinate on top
  factor: # calculate these from data
  offset: # calculate these from data


Train:
  lr: 
  w_decay:
  lr_decay:
  step_size: 1000 # lr decay step size
  batch_size: 16
  max_iters: 50000
  print_output: True
  print_freq: 100


PSF:
  calib_file: '/mnt/sda1/SMLAT/data/KonradPSF/splines/bead_3dcal.mat'
  psf_size: 31
  photon_scale: 7000 # i guess max numbeor of photons
  z_scale: 700
  pixel_size_xy:
    - 65
    - 65

Evaluation:
  ground_truth: True




Hardware:
  device: cuda:0
  device_simulation: cuda:0
  num_worker_train: 4
  torch_threads: 4
  unix_niceness: 0

InOut:
  experiment_out: '/mnt/sda1/SMLAT/training_runs/'
  calibration_file: ''
Meta:
  version: