

Simulation:
  train_size: 128 # size of the images network see
  use_cell_bg: False
  density: 4 
  margin_empty: 0.05 # what percent of the image you want to leave empty on the image
  z_prior:
    - -1
    - 1
  survival_prob: # only used if there is local context, so in our case it is not used
  min_photon: 0.428 # intensity distributions sampled from (min_ph, 1)
  camera: 'sCMOS'
  perlin_noise: False
  perlin_noise_factor: 0.2 # what fraction of bg photons you want to multiply to get PN noise map
  perlin_noise_res: 64
  baseline: 100
  bg_values: 110
  e_per_adu: 0.3 # e per adu of the camera
  qe: 1 # quantum efficiency
  spurious_c: 0.000 # not sure what this is
  sig_read: 0.001 # sigma of the read noise
  robust_training: False


Network:
  n_filters: 48
  n_stages: 2
  padding: 1
  kernel_size: 3
  sig_pred: True
  psf_pred: True
  local_context: False # This will just use 1 frame for context, always False for our use-case
  use_coordconv: False # Use if you want to add cell-bg coordinate on top
  factor: 120.0 # calculate these from data
  offset: 100.0 # calculate these from data


Train:
  lr: 0.0006
  w_decay: 0.1
  lr_decay: 0.9
  step_size: 1000 # lr decay step size
  batch_size: 16
  max_iters: 50000
  print_output: True
  print_freq: 100
  photon_filter: True
  photon_filter_threshold: 100
  P_locs_cse: True # uses cross-entropy loss that is not found in decode
  robust_training: False # Not relevant so far 
  clip_gradient_max_norm: 0.03


PSF:
  calib_file: '/mnt/sda1/SMLAT/data/KonradPSF/splines/bead_3dcal.mat'
  psf_size: 41 # kinda irrelevant for spline model psf
  photon_scale: 7000 # i guess max numbeor of photons
  z_scale: 400 # what range of values you want to have z emitters in 
  pixel_size_xy:
    - 65
    - 65

Evaluation:
  #ground_truth: True
  number_images: 1024 # number of images to do eval on
  eval_size: 128 # size of the evaluation image
  molecules_per_img: 4 # density used in the prob_map creation before sampling coordinates
  margin_empty: 0.05 # leave out the boundary
  use_cellbg: False
  cellbg_dir: None  # directory of mask you would like to use for cell bg coord
  candidate_threshold: 0.3
  nms_threshold: 0.7
  print_result: False
  batch_size: 4
  padded_background: 110 # we will get back to this padded value later






Hardware:
  device: cuda:0
  device_simulation: cuda:0
  num_worker_train: 4
  torch_threads: 4
  unix_niceness: 0

InOut:
  experiment_out: '/mnt/sda1/SMLAT/training_runs/'
  calibration_file: ''
  filename: '/mnt/sda1/SMLAT/training_runs/model_20230411'
Meta:
  version: